### ISSUE TITLE
Adapt to new `-Xmixin-force-forwarders` settings

### ISSUE THREAD

**Issue by adriaanm** [scala-js/scala-2.12-junit-mixin-plugin#14]
https://github.com/scala/scala/pull/5369 removed `nowarnDefaultJunitMethods`, so at least this will need to be fixed /cc @lrytz

**Comment by sjrd** [comment]
Well the PR you're citing actually supersedes this compiler plugin entirely, so we don't need to ever compile this plugin for RC1. Basically it has become useless, and should not be used with RC1.

**Comment by adriaanm** [comment]
Even better!

**Comment by SethTisue** [comment]
will do
